version: "3"

services:
  postgres:
    image: postgres:alpine
    container_name: kfc_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migration/up.sql:/docker-entrypoint-initdb.d/up.sql

  go_app:
      build:
        context: .
        dockerfile: Dockerfile  
      container_name: kfc_be
      restart: always
      environment:
        - DB_HOST=postgres
        - DB_PORT=5432
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
        - DB_NAME=${DB_NAME}
      ports:
        - "8080:8080"  
      depends_on:
        - postgres
volumes:
  postgres_data:
